language: go

go: 1.7.1

sudo: false

before_script:
  - go get -u github.com/golang/lint/golint

script:
  - go test -v --race

after_script:
  - test -z "$(gofmt -s -l -w . | tee /dev/stderr)"
  - test -z "$(golint ./...     | tee /dev/stderr)"
  - go vet ./...

os:
  - linux

notifications:
  email: false
